export interface Member {
    membeR_ID: number;
    orG_MEMBER_ID?: number | null;
    membeR_NO?: number | null;
    status?: number | null;
    title?: string | null;
    name?: string | null;
    firsT_NAME?: string | null;
    middlE_NAME?: string | null;
    lasT_NAME?: string | null;
    addresS_1?: string | null;
    addresS_2?: string | null;
    countrY_CODE?: string | null;
    ziP_CODE?: string | null;
    city?: string | null;
    phonE_1?: string | null;
    phonE_2?: string | null;
    phonE_3?: string | null;
    email?: string | null;
    cpr?: string | null;
    cluB_STATUS_ID?: number | null;
    cluB_START?: Date | string | null;
    cluB_TITLE_LEVEL?: number | null;
    orG_TITLE_LEVEL?: number | null;
    totaL_BRONZE?: number | null;
    totaL_SILVER?: number | null;
    totaL_GOLD?: number | null;
    totaL_MASTER?: number | null;
    lasT_ORG_UPDATE?: Date | string | null;
    paiD_YTD?: number | null;
    piN_TYPE?: number | null;
    iS_ADDRESS_OK?: boolean | null;
    iS_DEAD?: boolean | null;
    haS_STATUS_CHANGE?: boolean | null;
    futurE_STATUS_DATE?: Date | string | null;
    futurE_STATUS?: number | null;
    remotE_LOCK?: boolean | null;
    cluB_NAME?: string | null;
    namE_CHANGED?: Date | string | null;
    addresS_1_CHANGED?: Date | string | null;
    addresS_2_CHANGED?: Date | string | null;
    ziP_CODE_CHANGED?: Date | string | null;
    phonE_1_CHANGED?: Date | string | null;
    phonE_2_CHANGED?: Date | string | null;
    phonE_3_CHANGED?: Date | string | null;
    emaiL_CHANGED?: Date | string | null;
    cpR_CHANGED?: Date | string | null;
    statuS_CHANGED?: Date | string | null;
    lasT_CHANGED_BY?: string | null;
    iS_PRIMARY_CLUB?: boolean | null;
    birthday?: Date | string | null;
    dbF_OPRETTET_DATO?: Date | string | null;
    sidsT_RETTET?: Date | string | null;
    vedligeholdeR_STAMDATA?: boolean | null;
    hac?: number | null;
    haC_CHANGED?: Date | string | null;
    mP_TITLE_CHANGED?: Date | string | null;
}