export interface Member {
    memberId: number;
    orgMemberId?: number | null;
    memberNo?: number | null;
    status?: number | null;
    title?: string | null;
    name?: string | null;
    firstName?: string | null;
    middleName?: string | null;
    lastName?: string | null;
    address1?: string | null;
    address2?: string | null;
    countryCode?: string | null;
    zipCode?: string | null;
    city?: string | null;
    phone1?: string | null;
    phone2?: string | null;
    phone3?: string | null;
    email?: string | null;
    cpr?: string | null;
    clubStatusId?: number | null;
    clubStart?: Date | string | null;
    clubTitleLevel?: number | null;
    orgTitleLevel?: number | null;
    totalBronze?: number | null;
    totalSilver?: number | null;
    totalGold?: number | null;
    totalMaster?: number | null;
    lastOrgUpdate?: Date | string | null;
    paidYtd?: number | null;
    pinType?: number | null;
    isAddressOk?: boolean | null;
    isDead?: boolean | null;
    hasStatusChange?: boolean | null;
    futureStatusDate?: Date | string | null;
    futureStatus?: number | null;
    remoteLock?: boolean | null;
    clubName?: string | null;
    nameChanged?: Date | string | null;
    address1Changed?: Date | string | null;
    address2Changed?: Date | string | null;
    zipCodeChanged?: Date | string | null;
    phone1Changed?: Date | string | null;
    phone2Changed?: Date | string | null;
    phone3Changed?: Date | string | null;
    emailChanged?: Date | string | null;
    cprChanged?: Date | string | null;
    statusChanged?: Date | string | null;
    lastChangedBy?: string | null;
    isPrimaryClub?: boolean | null;
    birthday?: Date | string | null;
    dbfOprettetDato: Date | string;
    sidstRettet?: Date | string | null;
    vedligeholderStamdata?: boolean | null;
    hac?: number | null;
    hasChanged?: Date | string | null;
    mpTitleChanged?: Date | string | null;
}